In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
df=pd.read_csv(r"C:\Users\ABC\OneDrive\Desktop\py\FMCG Assignment - 2\Raw Sales Data.csv")
df

,Month,Channel,Sub-Channels,Product Name,Category,Qty,Sales
0,01-Dec-20,Marketplace,AMAZON,ALOE + AMLA JUICE 1 L,Juices,"1,116","4,28,700"
1,01-Dec-20,Marketplace,AMAZON,ALOE + GARCINIA JUICE 1 L,Juices,"3,003","13,74,831"
2,01-Dec-20,Marketplace,AMAZON,ALOE VERA JUICE 1 L,Juices,"2,962","7,32,167"
3,01-Dec-20,Marketplace,AMAZON,ALOE VERA SKIN GEL 500 GM,Gourmet Nutrition,"1,004","3,77,100"
4,01-Dec-20,Marketplace,AMAZON,NEEM JUICE 1 L,Juices,555,"1,52,287"
...,...,...,...,...,...,...,...
219,01-Mar-21,Marketplace,Big Basket,ORGANIC GULKAND 300grams,Gourmet Nutrition,509,"1,65,426"
220,01-Mar-21,Marketplace,Flipkart,ALOE + GARCINIA JUICE 1 L,Juices,542,"2,48,830"
221,01-Mar-21,Marketplace,Flipkart,AMLA JUICE 1 L,Juices,645,"1,40,907"
222,01-Mar-21,Marketplace,Flipkart,GET SLIM JUICE 1 L,Juices,"1,242","4,36,043"
223,01-Mar-21,Marketplace,GOQII,RAW HONEY ( MADHU) 500 GRAMS,Gourmet Nutrition,971,"5,82,600"

In [20]:
df.to_csv("Raw Sales Data.csv", index=False)

In [16]:
df["Month"] = pd.to_datetime(df["Month"], format="%d-%b-%y")

In [10]:
print(df["Sales"].dtype)

object

In [18]:
df["Sales"] = df["Sales"].astype(str).str.replace(",", "").astype(int)

In [27]:
df["Qty"] = df["Qty"].astype(str).str.replace(",", "").astype(int)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Month         224 non-null    datetime64[ns]
 1   Channel       224 non-null    object
 2   Sub-Channels  224 non-null    object
 3   Product Name  224 non-null    object
 4   Category      224 non-null    object
 5   Qty           224 non-null    int64
 6   Sales         224 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 12.4+ KB

#### 1. Monthwise number of quantities sold

In [29]:
monthly_qty = df.groupby(by=["Month"])[["Qty"]].sum()
monthly_qty

              Qty
Month
2020-12-01  85427
2021-01-01  67732
2021-02-01  76393
2021-03-01  80229

#### 2. Category wise Qty sold

In [30]:
category_qty = df.groupby(by=["Category"])[["Qty"]].sum()
category_qty

                         Qty
Category
Functional nutrition   42354
Gourmet Nutrition      89279
Juices                178148

#### 3. Sub-channel wise total sales

In [31]:
sub_Tsales = df.groupby(by=["Sub-Channels"])[["Sales"]].sum()
sub_Tsales

                      Sales
Sub-Channels
AMAZON             35606804
Big Basket          1207522
D2C                28047538
Flipkart            3770415
GOQII                582600
Offline - Central    375332
Offline - East       811146
Offline - MT        6257948
Offline - South     3446395
Offline - West      6441427
Offline -North      1206564

#### 4. Highest sale in which month

In [32]:
high_sales_month = df.groupby(by=["Month"])[["Sales"]].sum().sort_values(by="Sales", ascending=False).head(1)
high_sales_month

               Sales
Month
2021-03-01  25127827

#### 5. Highest selling product (based on sales) (packaging quantity doesn't matter. Ex. consider "GET SLIM
#### JUICE 1 L" and "GET SLIM JUICE 500 ML" as one product)

In [33]:
df["Product"] = df["Product Name"].str.replace(r"\s\d+\s?(ML|L|KG|G)", "", regex=True)
top_product = pd.DataFrame(df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(1))
top_product

                          Sales
Product
ALOE + GARCINIA JUICE  12249252

#### 6. List of different products company is offering (packaging quantity doesn't matter. Ex. consider "GET
#### SLIM JUICE 1 L" and "GET SLIM JUICE 500 ML" as one product)

In [34]:
df["Product_Name"] = df["Product"].str.replace(r"\s\d+\s?(ML|L|KG|G)","",regex=True)
unique_product = pd.DataFrame(df["Product_Name"].unique(),columns=["Different Products"])
unique_product

                            Different Products
0                            ALOE + AMLA JUICE
1                        ALOE + GARCINIA JUICE
2                              ALOE VERA JUICE
3                          ALOE VERA SKIN GELM
4                                   NEEM JUICE
5                                   NONI JUICE
6                      SLIM SHAKE - CHOCOLATEM
7                          SLIM SHAKE - MANGOM
8                               TRIPHALA JUICE
9                            TULSI GILOY JUICE
10                           WHEAT GRASS JUICE
11                                  AMLA JUICE
12                              GET SLIM JUICE
13                             HIMALAYA OILRMS
14                             VIGOR MAX JUICE
15                  ORGANIC JAGGERY POWDERRAMS
16                APPLE CIDER VINEGAR500 grams
17                          VIRGIN COCONUT OIL
18                          KARELA JAMUN JUICE
19    MASALA SUPERGRAIN MIX ENERGYM ( OFFLINE)
20  MASALA SUPERGRAIN MIX IMMUNITYM ( OFFLINE)
21                          AMLA + GILOY JUICE
22                              DIA FREE JUICE
23                           IMMUNE CARE JUICE
24             MASALA SUPERGRAIN MIX IMMUNITYM
25                    ORGANIC GULKAND 300grams
26                   VEGAN PROTEIN - CHOCOLATE
27                   GET SLIM CAPSULES 60 CAPS
28                      RAW HONEY ( MADHU)RAMS

In [35]:
with pd.ExcelWriter("Sales_Report.xlsx") as writer:

    # Sheet 1
    monthly_qty.to_excel(writer, sheet_name="Monthly Qty")
    #Sheet 2
    category_qty.to_excel(writer, sheet_name="Category Qty")
    #Sheet 3
    sub_Tsales.to_excel(writer, sheet_name="Top Sales")
    #Sheet 4
    high_sales_month.to_excel(writer, sheet_name="High Sales Month")
    #Sheet 5
    top_product.to_excel(writer, sheet_name="Top Product")
    #Sheet 6
    unique_product.to_excel(writer, sheet_name="All Product")

In [40]:
df2 = pd.read_excel("Sales_Report.xlsx",sheet_name="Category Qty")
df2

               Category     Qty
0  Functional nutrition   42354
1     Gourmet Nutrition   89279
2                Juices  178148